### 导入包与数据

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
kobe=pd.read_csv(r"C:\Users\27968\Desktop\学习\计算机\机器学习与数据挖掘\kobe_data.csv")

In [23]:
kobe

,action_type,combined_shot_type,lat,loc_x,loc_y,lon,minutes_remaining,period,playoffs,season,...,shot_distance,shot_made_flag,shot_type,shot_zone_area,shot_zone_basic,shot_zone_range,game_date,matchup,opponent,shot_id
0,Jump Shot,Jump Shot,33.9723,167,72,-118.1028,10,1,0,2000-01,...,18,NaN,2PT Field Goal,Right Side(R),Mid-Range,16-24 ft.,2000-10-31,LAL @ POR,POR,1
1,Jump Shot,Jump Shot,34.0443,-157,0,-118.4268,10,1,0,2000-01,...,15,0.0,2PT Field Goal,Left Side(L),Mid-Range,8-16 ft.,2000-10-31,LAL @ POR,POR,2
2,Jump Shot,Jump Shot,33.9093,-101,135,-118.3708,7,1,0,2000-01,...,16,1.0,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,2000-10-31,LAL @ POR,POR,3
3,Jump Shot,Jump Shot,33.8693,138,175,-118.1318,6,1,0,2000-01,...,22,0.0,2PT Field Goal,Right Side Center(RC),Mid-Range,16-24 ft.,2000-10-31,LAL @ POR,POR,4
4,Driving Dunk Shot,Dunk,34.0443,0,0,-118.2698,6,2,0,2000-01,...,0,1.0,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,2000-10-31,LAL @ POR,POR,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30692,Jump Shot,Jump Shot,33.9963,1,48,-118.2688,6,4,1,1999-00,...,4,0.0,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,2000-06-19,LAL vs. IND,IND,30693
30693,Tip Shot,Tip Shot,34.0443,0,0,-118.2698,6,4,1,1999-00,...,0,NaN,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,2000-06-19,LAL vs. IND,IND,30694
30694,Running Jump Shot,Jump Shot,33.8783,-134,166,-118.4038,3,4,1,1999-00,...,21,1.0,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,2000-06-19,LAL vs. IND,IND,30695
30695,Jump Shot,Jump Shot,33.7773,31,267,-118.2388,2,4,1,1999-00,...,26,0.0,3PT Field Goal,Center(C),Above the Break 3,24+ ft.,2000-06-19,LAL vs. IND,IND,30696
30696,Jump Shot,Jump Shot,33.9723,1,72,-118.2688,0,4,1,1999-00,...,7,0.0,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,2000-06-19,LAL vs. IND,IND,30697

### Question 1

In [5]:
px.scatter(kobe,x="loc_x",y="loc_y",color='shot_zone_area')

d:\Python\Lib\site-packages\plotly\express\_core.py:2065: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sf: grouped.get_group(s if len(s) > 1 else s[0])

In [6]:
px.scatter(kobe,x="loc_x",y="loc_y",color='shot_zone_basic')

d:\Python\Lib\site-packages\plotly\express\_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [7]:
px.scatter(kobe,x="loc_x",y="loc_y",color='shot_zone_range')

d:\Python\Lib\site-packages\plotly\express\_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

### Question 2

In [8]:
kobe.drop(columns=['game_event_id','game_id','team_name','team_id'],inplace=True)

### Question 3

In [24]:
print(kobe.describe())
print(kobe.describe(include=['object']))

                lat         loc_x         loc_y           lon  \
count  30697.000000  30697.000000  30697.000000  30697.000000
mean      33.953192      7.110499     91.107535   -118.262690
std        0.087791    110.124578     87.791361      0.110125
min       33.253300   -250.000000    -44.000000   -118.519800
25%       33.884300    -68.000000      4.000000   -118.337800
50%       33.970300      0.000000     74.000000   -118.269800
75%       34.040300     95.000000    160.000000   -118.174800
max       34.088300    248.000000    791.000000   -118.021800

       minutes_remaining        period      playoffs  seconds_remaining  \
count       30697.000000  30697.000000  30697.000000       30697.000000
mean            4.885624      2.519432      0.146562          28.365085
std             3.449897      1.153665      0.353674          17.478949
min             0.000000      1.000000      0.000000           0.000000
25%             2.000000      1.000000      0.000000          13.000000
50%             5.000000      3.000000      0.000000          28.000000
75%             8.000000      3.000000      0.000000          43.000000
max            11.000000      7.000000      1.000000          59.000000

       shot_distance  shot_made_flag       shot_id
count   30697.000000    25697.000000  30697.000000
mean       13.437437        0.446161  15349.000000
std         9.374189        0.497103   8861.604943
min         0.000000        0.000000      1.000000
25%         5.000000        0.000000   7675.000000
50%        15.000000        0.000000  15349.000000
75%        21.000000        1.000000  23023.000000
max        79.000000        1.000000  30697.000000
       action_type combined_shot_type   season       shot_type shot_zone_area  \
count        30697              30697    30697           30697          30697
unique          57                  6       20               2              6
top      Jump Shot          Jump Shot  2005-06  2PT Field Goal      Center(C)
freq         18880              23485     2318           24271          13455

       shot_zone_basic  shot_zone_range   game_date    matchup opponent
count            30697            30697       30697      30697    30697
unique               7                5        1559         74       33
top          Mid-Range  Less Than 8 ft.  2016-04-13  LAL @ SAS      SAS
freq             12625             9398          50       1020     1978

### Question 4

In [10]:
# 计算 shot_made_flag 的值计数
shot_counts = kobe['shot_made_flag'].value_counts().sort_index()

px.bar(x=shot_counts.index, y=shot_counts.values, 
             labels={'x': 'Shot Made Flag', 'y': '频数'},
        title='Shot Made Flag 分布')

In [11]:
total=len(kobe)
positive_ratio=shot_counts[1]/total
negative_ratio=shot_counts[0]/total

print(f"正样本比例: {positive_ratio:.2%}")
print(f"负样本比例: {negative_ratio:.2%}")

正样本比例: 37.35%
负样本比例: 46.36%

基本平衡

### Question 5

In [12]:
px.box(kobe,x='shot_made_flag',y='shot_distance',points='all')

比较：未命中投篮的距离中位数和四分位距都高于命中投篮,说明距离越远,命中率越低,这符合常理。

### Question 6

In [22]:
px.scatter(kobe,x='shot_distance',y='loc_y')

### Question 7

In [14]:
data=kobe.groupby(['combined_shot_type', 'shot_made_flag']).size()
data

combined_shot_type  shot_made_flag
Bank Shot           0.0                  25
                    1.0                  95
Dunk                0.0                  76
                    1.0                 980
Hook Shot           0.0                  59
                    1.0                  68
Jump Shot           0.0               12002
                    1.0                7708
Layup               0.0                1971
                    1.0                2561
Tip Shot            0.0                  99
                    1.0                  53
dtype: int64

In [15]:
data=kobe.groupby(['combined_shot_type', 'shot_made_flag']).size().unstack()
data

shot_made_flag        0.0   1.0
combined_shot_type
Bank Shot              25    95
Dunk                   76   980
Hook Shot              59    68
Jump Shot           12002  7708
Layup                1971  2561
Tip Shot               99    53

In [21]:
grouped_data = kobe.groupby(['combined_shot_type', 'shot_made_flag']).size().unstack()

px.bar(grouped_data, 
             barmode='group', #并排参数而不是堆叠 stack
             labels={'value': '频数', 'combined_shot_type': '投篮类型', 'shot_made_flag': '投篮结果'},
             title='不同投篮类型的命中和未命中频数')

d:\Python\Lib\site-packages\plotly\express\_core.py:2065: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.